language: python
python:
  - "2.7"
  - "3.6"
install:
  - sudo apt-get update
  - python setup.py install
script:
  - cd tests
  - python -m unittest discover --verbose --start-directory .
before_deploy:
  - python setup.py sdist
deploy:
  provider: pypi
  user: $DEPLOY_PYPI_USER
  password: $DEPLOY_PYPI_PASS
